export const STORAGE = process.env.STORAGE;
export const PORT = process.env.PORT;
export const DB_HOST = process.env.DB_HOST;
export const DB_PORT = process.env.DB_PORT;
export const DB_USER = process.env.DB_USER;
export const DB_PASSWORD = process.env.DB_PASSWORD;
export const DB_NAME = 'PartNetMobility';
export const TRUSTED_EMAIL_SUFFIX = ["@sfu.ca", "@ethz.ch", "@mail.utoronto.ca"];
export const TRUSTED_EMAIL_REGEX = ['^.*\.edu$', '^.*\.edu\.[a-zA-Z]+$']
